version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123   # phải trùng với code
      MYSQL_DATABASE: crm_app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: servlet_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Không cần vì bạn hardcode rồi
    depends_on:
      - db

volumes:
  db_data:
